"""
DeepSeek Harness (dsh) 平台适配器模块。
深度适配 DeepSeek 官方开源的模块化智能体框架 DeepSeek Harness (dsh)。
支持基于 Cordis 插件架构的 YAML 配置预设（Preset）、人设（Persona）、插件声明与任务指引导出。
"""
from pathlib import Path
from typing import Any, Dict, List
import yaml

from promptforge.models import PromptOutput, PromptSection, TemplateSections
from promptforge.adapters.base import BaseAdapter


class DeepSeekHarnessAdapter(BaseAdapter):
    """
    DeepSeek Harness (dsh) 智能体框架适配器。
    生成符合 DeepSeek Harness 规范的 YAML 智能体预设配置与面向 DeepSeek-V3/R1 的人设设定。
    """
    platform_name = 'deepseek_harness'
    max_tokens = 128000
    supports_system_prompt = True
    supports_tool_definitions = True
    output_format = 'yaml'

    def format_prompt(self, sections: TemplateSections, variables: Dict[str, Any]) -> List[PromptSection]:
        """
        格式化为 DeepSeek Harness 提示词片段。
        """
        result = []
        if sections.system:
            result.append(PromptSection(role="system", content=sections.system))
        for msg in sections.messages:
            result.append(PromptSection(role=msg.role, content=msg.content))
        return result

    def export(self, prompt: PromptOutput) -> str:
        """
        导出为 DeepSeek Harness (dsh) 标准的 YAML 预设配置 (Preset)。
        符合 Cordis 插件微内核架构规范。
        """
        system_text = ""
        user_text = ""

        for section in prompt.sections:
            if section.role == "system":
                system_text += section.content + "\n\n"
            elif section.role == "user":
                user_text += section.content + "\n\n"

        # 构建标准的 DeepSeek Harness 配置字典
        config: Dict[str, Any] = {
            "# framework": "DeepSeek Harness (dsh) - Cordis Microkernel Agent Runtime",
            "version": "1.0",
            "agent": {
                "name": prompt.template_name,
                "display_name": prompt.metadata.get("display_name", prompt.template_name),
                "category": prompt.category,
                "preset": "code" if prompt.category == "coding" else "standard",
                "default_model": "deepseek-chat",
                "reasoning_model": "deepseek-reasoner",
            },
            "persona": {
                "system_prompt": system_text.strip(),
                "rules": [
                    "遵循局部优先与直接执行原则 (Local-first & Direct execution)",
                    "代码修改提供精准的 Unified Diff 或可替换代码块",
                    "针对 DeepSeek-R1 模型优先采用确定性约束，避免冗余的 '逐步思考' 提示干扰模型原生思维链",
                ]
            },
            "runtime": {
                "plugins": [
                    {
                        "name": "@dsh/plugin-model-deepseek",
                        "config": {
                            "model": "deepseek-chat",
                            "temperature": 0.0,
                        }
                    },
                    {
                        "name": "@dsh/plugin-tool-filesystem",
                        "config": {
                            "sandbox": True,
                            "allow_write": True,
                        }
                    },
                    {
                        "name": "@dsh/plugin-tool-terminal",
                        "config": {
                            "timeout_ms": 30000,
                        }
                    },
                    {
                        "name": "@dsh/plugin-session-local"
                    }
                ]
            }
        }

        # 工具与函数扩展
        if prompt.tools:
            tool_list = []
            for tool in prompt.tools:
                tool_list.append({
                    "name": tool.name,
                    "description": tool.description,
                    "parameters": {
                        p.name: {
                            "type": p.type,
                            "required": p.required,
                            "description": p.description,
                        }
                        for p in tool.parameters
                    }
                })
            config["custom_tools"] = tool_list

        if user_text.strip():
            config["task"] = {
                "instruction": user_text.strip()
            }

        # 序列化为 YAML
        header = "# ========================================================\n"
        header += "# DeepSeek Harness (dsh) Agent Configuration\n"
        header += f"# Generated by PromptForge for {prompt.metadata.get('display_name', prompt.template_name)}\n"
        header += "# ========================================================\n\n"
        
        yaml_content = yaml.dump(config, allow_unicode=True, sort_keys=False, default_flow_style=False)
        return header + yaml_content

    def export_to_file(self, prompt: PromptOutput, output_path: Path) -> None:
        """
        导出到文件。支持保存为 dsh_agent.yaml、.dsh/settings.yaml 或纯提示词 Markdown。
        """
        if output_path.is_dir():
            target = output_path / f"dsh_{prompt.template_name}.yaml"
        else:
            target = output_path

        if target.suffix.lower() in ('.md', '.txt'):
            target.write_text(self.to_deepseek_prompt(prompt), encoding='utf-8')
        else:
            target.write_text(self.export(prompt), encoding='utf-8')

    def to_deepseek_prompt(self, prompt: PromptOutput) -> str:
        """
        导出直接面向 DeepSeek-V3 / DeepSeek-R1 的精简结构化 Markdown 提示词。
        符合 DeepSeek 官方提示词工程规范：直接明确、零样本 (Zero-shot) 优先、避免指令污染原生 CoT。
        """
        content = f"# DeepSeek Agent Specification - {prompt.metadata.get('display_name', prompt.template_name)}\n\n"

        for section in prompt.sections:
            if section.role == "system":
                content += f"## System Instructions\n\n{section.content}\n\n"
            elif section.role == "user":
                content += f"## Task\n\n{section.content}\n\n"
            else:
                content += f"## {section.role.capitalize()}\n\n{section.content}\n\n"

        if prompt.tools:
            content += "## Available Tools\n\n"
            for tool in prompt.tools:
                content += f"- `{tool.name}`: {tool.description}\n"

        return content.strip() + "\n"
